### Cadastro de novo cliente
POST http://localhost:8080/Cliente/register
Content-Type: application/json

{
  "Nome": "João da Silva",
  "Email": "joa21234121o@email.com",
  "Senha": "senha123",
  "CPF": "12345678909"
}

###

### Login do cliente
POST http://localhost:8080/Cliente/login
Content-Type: application/json

{
  "Email": "joa21234121o@email.com",
  "Senha": "senha123"
}

###