# For more info on HTTP files go to https://aka.ms/vs/httpfile
#@jwt_token =
### Cadastrar novo produto no estoque
POST http://localhost:8080/estoque-api/estoque/cadastrar
#Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "nome": "Produto Exemplo",
  "descricao": "Descrição do produto",
  "preco": 99.99,
  "quantidade": 10
}

###

### Listar produtos do estoque (com paginação opcional)
GET http://localhost:8080/estoque-api/estoque/produtos?page=1
#Authorization: Bearer {{jwt_token}}
Accept: application/json

###